#!/bin/bash
## Run this to generate the configure script

## Seperate version for mac is needed because Homebrew will install libtool as glibtool. This is caused by a name conflict with a proprietary Apple libtool-library (which does not fit our needs).

set -e
glibtoolize
aclocal
automake --add-missing
autoreconf
