## handcrafted Makefile

.PHONY:style clean

all: gadc

gadc: gadc.c liballuris.c liballuris.h
	gcc -Wall -Wextra -ggdb -I/usr/local/include/libusb-1.0 $< liballuris.c -lusb-1.0 -largp -o $@

style:
	find .. \( -name "*.m" -or -name "*.c" -or -name "*.h" \) -exec sed -i 's/[[:space:]]*$$//' {} \;
	astyle --style=gnu -s2 -n gadc.c liballuris.c liballuris.h

clean:
	rm -f gadc